//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcatsManager.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.ServicesOrder = new HashSet<ServicesOrder>();
        }
    
        public int IDOrder { get; set; }
        public string CodeOrder { get; set; }
        public Nullable<System.DateTime> DataCrate { get; set; }
        public Nullable<int> CodeClient { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DataClosing { get; set; }
        public Nullable<int> TimeRental { get; set; }
        public Nullable<System.TimeSpan> TimeOrder { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual OrderStatus OrderStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServicesOrder> ServicesOrder { get; set; }
    }
}
